INSERT INTO `book` (`id_user`, `title`, `author`, `description`, `id_state`, `photo`) VALUES
(1, 'Esther', 'Alabaster', 'Cet ouvrage de la collection Alabaster présente le livre biblique d\'Esther sous un angle artistique unique. Il ne s\'agit pas d\'une simple lecture religieuse, mais d\'une expérience visuelle où la typographie moderne et les photographies minimalistes s\'entrelacent avec le texte sacré. L\'histoire d\'Esther, cette jeune femme juive devenue reine de Perse pour sauver son peuple, est ici magnifiée par une mise en page épurée. Les visuels capturent l\'essence de la royauté, du courage et du destin providentiel. C\'est un livre qui s\'adresse autant aux amateurs d\'art qu\'aux personnes en quête de spiritualité, transformant la lecture en une méditation contemplative sur la force intérieure et la foi.', 1, 'images/books/esther.jpg'),

(2, 'The Kinfolk Table', 'Nathan Williams', 'The Kinfolk Table est bien plus qu\'un livre de cuisine ; c\'est un manifeste sur l\'art de recevoir et la valeur des relations humaines. Nathan Williams nous emmène à la rencontre de créatifs du monde entier — chefs, photographes, designers — qui partagent leur vision du partage autour d\'une table. Le livre met l\'accent sur la simplicité : des recettes accessibles, des ingrédients de saison et, surtout, l\'importance de passer du temps de qualité avec ses proches. Les photographies, fidèles à l\'esthétique Kinfolk, sont d\'une beauté organique et apaisante. Chaque portrait est une invitation à ralentir, à savourer l\'instant présent et à redécouvrir le plaisir des repas partagés sans artifice, où la conversation compte autant que le contenu de l\'assiette.', 2, 'images/books/the-kinfolk-table.jpg'),

(3, 'Wabi Sabi', 'Beth Kempton', 'Dans cet essai inspirant, Beth Kempton explore le concept japonais du Wabi Sabi, un art de vivre qui célèbre la beauté de l\'imperfection, de l\'impermanence et de l\'inachevé. À travers ses voyages au Japon et ses réflexions personnelles, l\'autrice nous apprend à nous libérer de la quête épuisante de perfection imposée par la société moderne. Le livre propose des conseils pratiques pour appliquer cette philosophie à notre quotidien : simplifier notre intérieur, accepter nos échecs et trouver la paix dans la simplicité de la nature. C\'est un guide doux et profond qui invite à une véritable transformation intérieure, nous rappelant que c\'est précisément dans nos fêlures et dans la modestie des choses que réside la véritable richesse de l\'existence.', 1, 'images/books/wabi-sabi.jpg'),

(4, 'Milk & honey', 'Rupi Kaur', 'Lait et Miel est un recueil de poésie et de prose d\'une puissance émotionnelle rare, illustré par les dessins minimalistes de Rupi Kaur. Le livre est découpé en quatre chapitres : souffrir, aimer, rompre, guérir. Chaque partie traite d\'un aspect différent de la douleur et de la résilience. L\'autrice y aborde avec une franchise désarmante des thèmes tels que la violence, l\'abus, l\'amour, la perte et la féminité. Ses mots, courts et percutants, agissent comme une thérapie pour le lecteur, offrant du réconfort dans les moments de noirceur. C\'est une œuvre qui célèbre la capacité de l\'âme humaine à se reconstruire après l\'épreuve, transformant l\'amertume de la vie en une douceur nécessaire pour continuer à avancer.', 2, 'images/books/milk-and-honey.jpg'),

(1, 'Delight!', 'Justin Rossow', 'Delight! est une exploration spirituelle centrée sur la joie et l\'émerveillement que l\'on peut trouver dans une relation avec le divin. Justin Rossow s\'appuie sur des textes bibliques et des anecdotes vécues pour montrer que la foi ne doit pas être un fardeau ou une série d\'obligations, mais une source constante de délice. Le livre encourage les lecteurs à redécouvrir les petites merveilles du quotidien et à voir la main de Dieu dans l\'ordinaire. Par une écriture chaleureuse et engageante, l\'auteur propose des exercices de réflexion pour cultiver une attitude de gratitude. C\'est un ouvrage rafraîchissant qui invite à sortir de la routine spirituelle pour embrasser une vie plus vibrante, joyeuse et connectée à l\'essentiel.', 1, 'images/books/delight.jpg'),

(2, 'Milwaukee Mission', 'Elder Cooper Low', 'Ce récit relate l\'expérience d\'un jeune missionnaire dans la ville de Milwaukee. Elder Cooper Low partage les défis, les doutes mais aussi les moments de grâce rencontrés lors de son service. Au-delà de l\'aspect purement religieux, le livre est une immersion dans la réalité sociale de la ville, avec ses quartiers contrastés et ses habitants aux histoires de vie marquantes. L\'auteur décrit avec humilité son apprentissage de la patience, de l\'empathie et du don de soi. Les anecdotes sont parsemées de réflexions sur la croissance personnelle et la découverte d\'une vocation au service des autres. C\'est un témoignage sincère sur le passage à l\'âge adulte et sur la manière dont une expérience de terrain peut transformer radicalement la vision du monde d\'un jeune homme.', 2, 'images/books/milwaukie-mission.jpg'),

(3, 'Minimalist Graphics', 'Julia Schonlau', 'Minimalist Graphics est une anthologie visuelle qui célèbre l\'efficacité et l\'élégance de la simplicité dans le design graphique contemporain. Julia Schonlau a rassemblé une vaste collection de travaux allant de l\'identité visuelle au design de packagings, en passant par l\'affiche. Le livre démontre comment, en utilisant un minimum d\'éléments — une palette de couleurs restreinte, une typographie forte et un usage intelligent de l\'espace vide — on peut créer un impact maximal. Chaque projet présenté est analysé sous l\'angle de sa clarté et de sa capacité à communiquer un message essentiel sans superflu. C\'est une source d\'inspiration inestimable pour les designers et les créatifs qui cherchent à épurer leur style et à revenir à l\'essence même de la communication visuelle.', 1, 'images/books/minimalist-graphcs.jpg'),

(4, 'Hygge', 'Meik Wiking', 'Le livre du Hygge, écrit par le directeur de l\'Institut de recherche sur le bonheur de Copenhague, nous livre les secrets du bonheur à la danoise. Le Hygge n\'a pas de traduction littérale, mais il évoque une atmosphère de confort, de convivialité et de bien-être. Meik Wiking explique comment les Danois, malgré un climat rude, parviennent à être l\'un des peuples les plus heureux au monde. À travers des conseils sur l\'éclairage (la magie des bougies), la nourriture réconfortante, les vêtements douillets et l\'importance du foyer, l\'auteur nous donne les clés pour intégrer cette philosophie dans notre propre vie. Richement illustré et plein d\'humour, cet ouvrage est un guide pratique pour savourer les plaisirs simples et créer des moments de chaleur humaine, même au cœur de l\'hiver.', 2, 'images/books/hygge.jpg'),

(1, 'Innovation', 'Matt Ridley', 'Dans cet essai magistral, Matt Ridley analyse l\'histoire de l\'innovation humaine et démontre qu\'elle n\'est pas le fruit d\'un génie isolé, mais un processus collectif et évolutif. L\'innovation survient lorsque les idées se rencontrent et "font l\'amour", créant ainsi de nouvelles solutions aux problèmes de l\'humanité. L\'auteur parcourt des millénaires de progrès, de l\'invention de l\'agriculture à l\'intelligence artificielle, en passant par la machine à vapeur et les vaccins. Il souligne l\'importance de la liberté d\'échange et de la collaboration pour favoriser la créativité. Ridley plaide pour une vision optimiste du futur, affirmant que tant que nous permettrons aux idées de circuler librement, nous trouverons les moyens de surmonter les défis énergétiques, environnementaux et sanitaires auxquels nous faisons face.', 1, 'images/books/innovation.jpg'),

(2, 'Psalms', 'Alabaster', 'Le livre des Psaumes, pilier de la poésie lyrique biblique, trouve ici une expression visuelle magnifique grâce au travail du studio Alabaster. Cette édition transforme les chants de louange, de lamentation et de gratitude en un objet d\'art contemporain. Chaque psaume est mis en page avec une attention méticuleuse portée au rythme du texte, accompagné d\'images de paysages naturels et de compositions abstraites qui évoquent les émotions décrites par le psalmiste. L\'objectif est de ralentir la lecture pour permettre une immersion sensorielle complète. Que l\'on aborde ce livre sous l\'angle de la foi ou de la littérature classique, il offre une expérience contemplative puissante, rappelant la profondeur universelle des questionnements humains sur la douleur, la joie et le sacré.', 2, 'images/books/psalms.jpg'),

(3, 'Thinking, Fast & Slow', 'Daniel Kahneman', 'Système 1, Système 2 : les deux vitesses de la pensée est une œuvre révolutionnaire du prix Nobel d\'économie Daniel Kahneman. Il y expose les recherches de toute une vie sur les mécanismes du jugement et de la prise de décision. Le livre explique la dualité entre notre pensée rapide, intuitive et émotionnelle (Système 1) et notre pensée lente, plus délibérée et logique (Système 2). Kahneman révèle les nombreux biais cognitifs qui influencent nos choix au quotidien, souvent à notre insu : excès de confiance, aversion pour la perte, effet d\'ancrage. En comprenant comment ces raccourcis mentaux fonctionnent, nous pouvons apprendre à mieux raisonner et à éviter les erreurs de jugement coûteuses. C\'est un ouvrage dense mais fascinant qui change radicalement notre perception de notre propre esprit et de nos comportements.', 1, 'images/books/thinking-fast-and-slow.jpg'),

(4, 'A Book Full Of Hope', 'Rupi Kaur', 'Ce nouvel opus de Rupi Kaur est une célébration de l\'optimisme et de la force intérieure. Fidèle à son style minimaliste, l\'autrice propose des réflexions courtes et des poèmes qui agissent comme des mantras de guérison. Après avoir exploré la douleur et le traumatisme dans ses précédents ouvrages, elle se tourne ici vers la lumière, la croissance personnelle et la sororité. Le livre encourage le lecteur à s\'aimer inconditionnellement et à trouver l\'espoir même dans les circonstances les plus difficiles. Les illustrations à l\'encre noire complètent parfaitement les textes, créant un espace de paix et de respiration. C\'est un guide précieux pour tous ceux qui traversent une période de transition ou de doute, offrant une main tendue vers un avenir plus serein et épanoui.', 2, 'images/books/a-book-of-full-hope.jpg'),

(1, 'The Subtle Art Of Not Giving a Fuck', 'Mark Manson', 'L\'Art subtil de s\'en foutre est un guide de développement personnel "à contre-courant" qui rejette la tyrannie du positivisme à tout prix. Mark Manson soutient que pour vivre une vie meilleure, nous ne devons pas essayer de tout rendre positif, mais apprendre à mieux choisir ce qui nous importe vraiment. Il nous invite à accepter nos limites et à embrasser nos peurs et nos incertitudes. À travers des anecdotes percutantes et un langage cru, l\'auteur explique que la souffrance est inévitable et que la clé du bonheur réside dans la résolution de problèmes qui font sens pour nous. C\'est un plaidoyer pour l\'honnêteté, la responsabilité personnelle et la recherche de valeurs solides. Un livre provocateur qui remet les pieds sur terre et aide à se concentrer sur l\'essentiel.', 1, 'images/books/the-subtitle-art-of.jpg'),

(2, 'Narnia', 'C.S Lewis', 'Le Lion, la Sorcière blanche et l\'Armoire magique est le premier tome (selon l\'ordre de publication) de la célèbre saga fantastique de C.S. Lewis. Il raconte l\'aventure de quatre frères et sœurs — Peter, Susan, Edmund et Lucy — qui découvrent un monde merveilleux caché au fond d\'une vieille armoire. Narnia est un pays plongé dans un hiver éternel par la maléfique Sorcière Blanche, attendant le retour du grand lion Aslan pour être libéré. Le récit est une épopée captivante mêlant mythologie, créatures magiques et combat entre le bien et le mal. Derrière le conte pour enfants se cachent des thèmes profonds sur le sacrifice, la trahison et la rédemption. C\'est une œuvre intemporelle qui continue d\'émerveiller les lecteurs de tous âges par son imagination débordante et sa richesse symbolique.', 2, 'images/books/narnja.jpg'),

(3, 'Company Of One', 'Paul Jarvis', 'Company of One remet en question la croyance selon laquelle "plus grand est toujours mieux" dans le monde des affaires. Paul Jarvis propose une approche alternative : rester petit pour gagner en liberté, en efficacité et en résilience. Il explique comment créer une entreprise rentable et durable qui ne cherche pas une croissance infinie, mais se concentre sur la qualité du travail et la satisfaction du client tout en préservant la vie personnelle de l\'entrepreneur. Le livre fournit des conseils stratégiques sur l\'automatisation, la gestion de la relation client et la définition de ses propres critères de succès. C\'est une lecture indispensable pour les freelances et les créatifs qui souhaitent construire une carrière épanouissante sans sacrifier leur bien-être sur l\'autel du scaling à outrance.', 1, 'images/books/company-of-one.jpg'),

(4, 'The Two Towers', 'J.R.R Tolkien', 'Les Deux Tours est le deuxième volet de la trilogie monumentale Le Seigneur des Anneaux. Après la dissolution de la Communauté de l\'Anneau, l\'histoire se divise en deux fils narratifs épiques. D\'un côté, Aragon, Legolas et Gimli poursuivent les Orques pour sauver leurs amis Hobbits et se retrouvent impliqués dans la défense du royaume du Rohan contre les armées de Saroumane. De l\'autre, Frodon et Sam continuent leur périlleux voyage vers le Mordor pour détruire l\'Anneau Unique, guidés par la créature ambiguë Gollum. Tolkien déploie toute la richesse de sa Terre du Milieu, avec ses langues, ses cultures et ses batailles légendaires comme celle du Gouffre de Helm. C\'est un chef-d\'œuvre de la fantasy qui explore le courage face à une noirceur écrasante et la force des liens d\'amitié.', 2, 'images/books/the-two-towers.jpg');